# Generated by Django 6.0.6 on 2026-07-10 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_shipping_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
