# Generated by Django 6.0.6 on 2026-07-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_payment_method_remove_order_produ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20),
        ),
    ]
