# Generated by Django 6.0.6 on 2026-07-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='origin',
            field=models.CharField(default='nth', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='nth', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='nth', max_length=10),
        ),
    ]
