# Generated by Django 6.0.6 on 2026-07-15 12:41

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='random_order',
            field=models.FloatField(default=products.models.get_random_value),
        ),
    ]
