# Generated by Django 6.0.6 on 2026-07-17 09:15

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_random_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='random_order',
            field=models.FloatField(blank=True, default=products.models.get_random_value),
        ),
    ]
